# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with unittest
        working-directory: ./app
        run: python -m unittest discover tests
      - name: try publish
        run: semantic-release publish -D branch=main
    
  release:
    runs-on: ubuntu-latest
    concurrency: release
    needs: Quality
    steps:
    - uses: actions/checkout@v2
      with:
        ref : main
    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository_username: __token__
      